// Creamos el Modelo Schema  de la BD
const applicantSchema = new mongoose.Schema({
    workbefore: {type:String, enum: ['Yes', 'No']},
    payrange: String,
    desposition: {type:String, enum: ['Costumer Service Representative', 'Spanish Costumer Service', 'Claims Representative', 'Salex Executive', 'Other']},
    name: String,
    psourname: String,
    msourname: String,
    dob: Date,
    age: Number,
    gender: {type:String, enum:['Male', 'Female']},
    pofbirth: String,
    nationality: String,
    city: {type:String, enum: ['Tijuana', 'Tecate', 'Mexicali', 'Rosarito', 'Ensenada']},
    satate: {type:String, enum: ['Baja California', 'Other']},
    zipcode: Number,
    street: String,
    streetNumber: String,
    appartNumber: String,
    homePhone: Number,
    mobileNumber: Number,
    secondaryPhone: String,
    radio: String,
    email: String,
    relation: {type: String, enum: ['Single', 'Married', 'Separated', 'Living Together']},
    spouseName: String,
    childrens:{ type: String, enum: ['1', '2', '3', '4', '5', 'Other']},
    fatherName: String,
    motherName: String,
    emergencyContact: String,
    relationshipContact: String,
    relcontactPhone: String,
    dependentYou: String,
    timeResident: String,
    education: String,
    school: String,
    graduationDate: Date,
    degree: String,
    englishProficiency: Number,
    englishWriteLevel: String,
    computerProficiency:{type: String, enum:['Basic', 'Intermediate', 'Advanced']},
    validVisa:{type: String, enum: ['Yes', 'No']},
    bodyTattos:{type: String, enum: ['Yes', 'No']},
    memberClub: String,
    criminalRecord:{type: String, enum: ['Yes', 'No']},
    prisionMexico:{type: String, enum: ['Yes', 'No']},
    shift:{type: String, enum: ['Morning', 'Afternoon', 'Night']},
    callWork:{type: String, enum: ['Yes', 'No']},
    nightShift:{type: String, enum: ['Yes', 'No']},
    refName: String,
    refOccupation: String,
    refPhone: String,
    refKnow: String,
    refEmail: String,
    workExperince:{type: String, enum: ['Yes', 'No']},
    companyName: String,
    companyCountry: String,
    companyDate: Date,
    leaveJob: String,
    jobTitle: String,
    supervisorName: String,
    
});

// Creamos el Modelo 

const Applicant = mongoose.model('Applicant', applicantSchema);

module.exports = Applicant;